export const functionsData = [
  {
    id: "1",
    name: ".ASK",
    description:
      "Ask a question to the AI, and optionally provide input and specify output format.(without web search capability)",
    parameters: [
      {
        name: "query",
        description: "The query or question to be asked.",
        dataType: "string",
        example: ["What is the population of Japan?"],
        required: true,
      },
      {
        name: "input",
        description: "Additional input like a cell reference or table.",
        dataType: "Any",
        example: ["A1", "B1:B10", "A1:H35"],
        required: false,
      },
      {
        name: "output_format",
        description: "Defines the output format: 0: Single Cell, 1: Vertical List, 2: Horizontal List, 3: Table",
        dataType: "Integer",
        required: false,
        example: [0, 3],
      },
    ],
    examples: [
      "=MINDCASE.ASK(”Find all the recent mergers in the US banking industry, give me the counterparrties involved, the deal amount and the purpose of the deal?”,, 3 )",
      "=MINDCASE.ASK(”I have computed these ratios looking at the financial statements of a B2C edtech company, what other ratios should I look at, give me the metric and their definitions, A2:H4, 3”)",
      "=MINDCASE.ASK (”Extract all the key customer pain points from these comments”, A2:A100)",
      '=MINDCASE.ASK("Give me list of companies which have been in s&p 500 since its incorporation",)',
      "=MINDCASE.ASK(”Give me list of current S&P 500 companies”,)",
    ],
  },
  {
    id: "10",
    name: ".ASK_WEB",
    description:
      "Ask a question to the AI, and optionally provide input and specify output format (with web search capability)",
    parameters: [
      {
        name: "query",
        description: "The query or question to be asked.",
        dataType: "string",
        example: ["What is the population of Japan?"],
        required: true,
      },
      {
        name: "input",
        description: "Additional input like a cell reference or table.",
        dataType: "Any",
        example: ["A1", "B1:B10", "A1:H35"],
        required: false,
      },
      {
        name: "output_format",
        description: "Defines the output format: 0: Single Cell, 1: Vertical List, 2: Horizontal List, 3: Table",
        dataType: "Integer",
        required: false,
        example: [0, 3],
      },
    ],
    examples: [
      "=MINDCASE.ASK_WEB(”Find all the recent mergers in the US banking industry, give me the counterparrties involved, the deal amount and the purpose of the deal?”,, 3 )",
      "=MINDCASE.ASK_WEB(”I have computed these ratios looking at the financial statements of a B2C edtech company, what other ratios should I look at, give me the metric and their definitions, A2:H4, 3”)",
      "=MINDCASE.ASK_WEB (”Extract all the key customer pain points from these comments”, A2:A100)",
      '=MINDCASE.ASK_WEB("Give me list of companies which have been in s&p 500 since its incorporation",)',
      "=MINDCASE.ASK_WEB(”Give me list of current S&P 500 companies”,)",
    ],
  },
  {
    id: "2",
    name: ".EXTRACT_FROM_WEBPAGE",
    description: "Extract information and answer questions from a given source webpage without pagination.",
    parameters: [
      {
        name: "query",
        description: "A specific query to extract data from the webpage.",
        dataType: "string",
        example: ["Revenue of Tesla in 2022"],
        required: true,
      },
      {
        name: "source_url",
        description: "The URL of the webpage to extract data from.",
        dataType: "string",
        example: ["https://zoominfo.com"],
        required: true,
      },
      {
        name: "output_format",
        description: "Defines the output format: 0: Single Cell, 1: Vertical List, 2: Horizontal List, 3: Table",
        dataType: "Integer",
        example: [0, 1, 2, 3],
        required: false,
      },
    ],
    examples: [
      '=MINDCASE.EXTRACT_FROM_WEBPAGE("Get the names and brief description of all the companies listed here", "https://builtin.com/articles/fintech-companies-startups-to-know", 3)',
      '=MINDCASE.EXTRACT_FROM_WEBPAGE("Give me the list of companies, their employee count and where it\'s located", "https://www.ambitionbox.com/medical-equipment-companies-in-india", 3)',
      '=MINDCASE.EXTRACT_FROM_WEBPAGE("Current exchange rate USDINR", "https://www.xe.com/currencyconverter/convert/?Amount=1&From=USD&To=INR")',
      '=MINDCASE.EXTRACT_FROM_WEBPAGE("Countries in EU", "https://www.europa.eu", 2)',
      '=MINDCASE.EXTRACT_FROM_WEBPAGE("Current stock price of Amazon", "https://finance.yahoo.com")',
    ],
  },
  {
    id: "13",
    name: ".EXTRACT_WITH_PAGINATION",
    description: "Extract information and answer questions from a given source webpage with pagination.",
    parameters: [
      {
        name: "query",
        description: "A specific query to extract data from the webpage.",
        dataType: "string",
        example: ["Revenue of Tesla in 2022"],
        required: true,
      },
      {
        name: "source_url",
        description: "The URL of the webpage to extract data from.",
        dataType: "string",
        example: ["https://zoominfo.com"],
        required: true,
      },
      {
        name: "output_format",
        description: "Defines the output format: 0: Single Cell, 1: Vertical List, 2: Horizontal List, 3: Table",
        dataType: "Integer",
        example: [0, 1, 2, 3],
        required: false,
      },
      {
        name: "pages",
        description: "Number of pages to be scraped",
        dataType: "Integer",
        example: [4, 7],
        required: false,
      },
    ],
    examples: [
      '=MINDCASE.EXTRACT_WITH_PAGINATION("Get the names and brief description of all the companies listed here", "https://builtin.com/articles/fintech-companies-startups-to-know", 3)',
      '=MINDCASE.EXTRACT_WITH_PAGINATION("Give me the list of companies, their employee count and where it\'s located", "https://www.ambitionbox.com/medical-equipment-companies-in-india", 3, 1)',
      '=MINDCASE.EXTRACT_WITH_PAGINATION("Current exchange rate USDINR", "https://www.xe.com/currencyconverter/convert/?Amount=1&From=USD&To=INR")',
      '=MINDCASE.EXTRACT_WITH_PAGINATION("Countries in EU", "https://www.europa.eu", 2)',
      '=MINDCASE.EXTRACT_WITH_PAGINATION("Current stock price of Amazon", "https://finance.yahoo.com")',
    ],
  },
  {
    id: "3",
    name: ".GET_COMPANY_DATA",
    description: "Retrieve specific data points about a company like revenue or employee count.",
    parameters: [
      {
        name: "company_name",
        description: "The name of the company.",
        dataType: "string",
        example: ["Microsoft", "A2"],
        required: true,
      },
      {
        name: "data_point",
        description: "The specific data point to retrieve (e.g., revenue, employees).",
        dataType: "string",
        example: ["Revenue", "Employee count", "B1"],
        required: true,
      },
      {
        name: "source",
        description: "The source of data.",
        dataType: "string",
        required: false,
        example: ["https://www.example.com/microsoft-reports"],
      },
      {
        name: "custom_instructions",
        description: "Additional instructions to refine the data retrieval process.",
        dataType: "string",
        required: false,
        example: ["Retrieve data from the 2023 report"],
      },
    ],
    examples: [
      '=MINDCASE.GET_COMPANY_DATA("Tesla", "Revenue")',
      '=MINDCASE.GET_COMPANY_DATA("Microsoft", "Employee count", "https://www.microsoft.com/reports")',
      '=MINDCASE.GET_COMPANY_DATA("Google", "Description", , "Summarize the company\'s mission")',
      '=MINDCASE.GET_COMPANY_DATA("Amazon", "Revenue", , "Retrieve revenue for 2022")',
      '=MINDCASE.GET_COMPANY_DATA("Apple", "Market capitalization", "https://finance.yahoo.com")',
    ],
  },
  {
    id: "4",
    name: ".STANDARDIZE_UNITS",
    description: "Convert various units of measurement into a specified standard unit.",
    parameters: [
      {
        name: "input",
        description: "The input value or range containing units to be standardized.",
        dataType: "Any",
        example: ["B2:B10", "5 kg"],
        required: true,
      },
      {
        name: "target_notation",
        description: "The desired unit or notation for standardization.",
        dataType: "string",
        example: ["$Mn", "miles", "Celsius"],
        required: true,
      },
    ],
    examples: [
      '=MINDCASE.STANDARDIZE_UNITS("5 kg", "grams")',
      '=MINDCASE.STANDARDIZE_UNITS(B1:B5, "liters")',
      '=MINDCASE.STANDARDIZE_UNITS("98 Fahrenheit", "Celsius")',
      '=MINDCASE.STANDARDIZE_UNITS("3 miles", "kilometers")',
      '=MINDCASE.STANDARDIZE_UNITS(A1:A3, "gallons")',
    ],
  },
  {
    id: "5",
    name: ".CLASSIFY",
    description: "Assigns input values to specified categories.",
    parameters: [
      {
        name: "input",
        description: "Value(s) to be classified.",
        dataType: "string",
        example: ["OpenAI"],
        required: true,
      },
      {
        name: "categories",
        description: "Defined groups or classes for classification.",
        dataType: "string",
        example: ["AI", "Crypto", "Cloud"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.CLASSIFY("OpenAI", "AI, Crypto, Cloud")'],
  },
  {
    id: "6",
    name: ".EXTRACT",
    description: "Retrieves specific data based on given instructions.",
    parameters: [
      {
        name: "input",
        description: "Excel data range or value to process.",
        dataType: "string",
        example: ["*AGR solutions is your technical partner."],
        required: true,
      },
      {
        name: "instructions",
        description: "Criteria or rules for extraction written in free-form text.",
        dataType: "string",
        example: ["Company name"],
        required: true,
      },
    ],
    examples: [
      '=MINDCASE.EXTRACT("*AGR solutions is your technical partner. We provide you with technical resources.", "Company name")',
    ],
  },
  {
    id: "7",
    name: ".TAG",
    description: "Assigns tags to input values.",
    parameters: [
      {
        name: "input",
        description: "Value(s) to be tagged.",
        dataType: "string",
        example: ["I loved the product, disappointed with delivery delays"],
        required: true,
      },
      {
        name: "tags",
        description: "Labels or identifiers to assign.",
        dataType: "string",
        example: ["Product - good", "Product - bad", "Delivery - good", "Delivery - bad"],
        required: true,
      },
    ],
    examples: [
      '=MINDCASE.TAG("I loved the product, disappointed with delivery delays", "Product - good, Product - bad, Delivery - good, Delivery - bad")',
    ],
  },
  {
    id: "8",
    name: ".SUMMARIZE",
    description: "Generates a concise summary of the input.",
    parameters: [
      {
        name: "input",
        description: "Excel data range or text to summarize.",
        dataType: "string",
        example: ["Private equity (PE) firms operate by raising capital..."],
        required: true,
      },
    ],
    examples: [
      '=MINDCASE.SUMMARIZE("Private equity (PE) firms operate by raising capital from institutional investors...")',
    ],
  },
  {
    id: "9",
    name: ".TRANSLATE",
    description: "Translates input into the target language.",
    parameters: [
      {
        name: "input",
        description: "Excel data range or text to translate.",
        dataType: "string",
        example: ["хелло"],
        required: true,
      },
      {
        name: "target_language",
        description: "Language for the translation.",
        dataType: "string",
        example: ["English"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.TRANSLATE("хелло", "English")'],
  },
  {
    id: "11",
    name: ".WORLD_BANK",
    description: "Retrieves specific data based on given instructions.",
    parameters: [
      {
        name: "query",
        description: "Input query in natural language.",
        dataType: "string",
        example: ["Give me the data for world hunger"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.WORLD_BANK("Give me the data for world hunger")'],
  },
  {
    id: "12",
    name: ".LATEST_STARTUP_FUNDING",
    description: "Retrieves specific data based on given instructions.",
    parameters: [],
    examples: ["=MINDCASE.LATEST_STARTUP_FUNDING()"],
  },
  {
    id: "14",
    name: ".YAHOO_FINANCE",
    description: "Extracts financial data from Yahoo Finance.",
    parameters: [
      {
        name: "company_name",
        description: "The name of the company.",
        dataType: "string",
        example: ["Microsoft", "A2"],
        required: true,
      },
      {
        name: "data_point",
        description: "The specific data point to retrieve (e.g., revenue, employees).",
        dataType: "string",
        example: ["Revenue", "Balance sheet", "B1"],
        required: true,
      },
      {
        name: "output_format",
        description: "Defines the output format: 0: Single Cell, 1: Vertical List, 2: Horizontal List, 3: Table",
        dataType: "Integer",
        required: false,
        example: [0, 3],
      },
      {
        name: "units",
        description: "Desired unit or notation for standardization",
        dataType: "string",
        required: false,
        example: ["INR Crore", "USD Million"],
      },
    ],
    examples: [
      '=MINDCASE.YAHOO_FINANCE("Tesla", "Revenue")',
      '=MINDCASE.YAHOO_FINANCE("Microsoft", "Employee count", 1)',
      '=MINDCASE.YAHOO_FINANCE("Amazon", "Revenue", )',
      '=MINDCASE.YAHOO_FINANCE("Apple", "Market capitalization", 3)',
    ],
  },
  {
    id: "15",
    name: ".LINKEDIN_URLS",
    description: "Extracts relevant Linkedin URLs based on user query",
    parameters: [
      {
        name: "query",
        description: "Keywords to find relevant people",
        dataType: "string",
        example: ["OpenAI CXOs", "A2"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.LINKEDIN_URLS("Mindcase Employees")'],
  },
  {
    id: "16",
    name: ".GET_LINKEDIN_DATA",
    description: "Extracts relevant details from a Linkedin URL.",
    parameters: [
      {
        name: "URL",
        description: "Provide the Linkedin URL of relevant person.",
        dataType: "string",
        example: ["https://www.linkedin.com/in/xyz/"],
        required: true,
      },
      {
        name: "data_point",
        description: "The specific data point to retrieve (e.g., revenue, employees).",
        dataType: "string",
        example: ["Revenue", "Employee count", "B1"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.GET_LINKEDIN_DATA("https://www.linkedin.com/in/xyz/", "Revenue")'],
  },
  {
    id: "17",
    name: ".GET_EMAIL",
    description: "Retrieves the email address of the relevant person.",
    parameters: [
      {
        name: "linkedin_url",
        description: "LinkedIn profile URL of the target person.",
        dataType: "string",
        example: ["https://www.linkedin.com/in/xyz/"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.GET_EMAIL("https://www.linkedin.com/in/relevant-person/")'],
  },
  {
    id: "17",
    name: ".GET_EMAIL",
    description: "Retrieves the email address of the relevant person.",
    parameters: [
      {
        name: "linkedin_url",
        description: "LinkedIn profile URL of the target person.",
        dataType: "string",
        example: ["https://www.linkedin.com/in/xyz/"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.GET_EMAIL("https://www.linkedin.com/in/relevant-person/")'],
  },
  {
    id: "19",
    name: ".ASK_DOC",
    description: "Answers a question about a document",
    parameters: [
      {
        name: "query",
        description: "Input query in natural language",
        dataType: "string",
        example: ["What is the value of the stock XYZ?"],
        required: true,
      },
      {
        name: "file_name",
        description: "Name of your uploaded file",
        dataType: "string",
        example: ["test.pdf"],
        required: true,
      },
      {
        name: "output_format",
        description: "Output style (0: cell, 1: cols, 2: rows, 3: table)",
        dataType: "number",
        example: [0],
        required: false,
      },
    ],
    examples: ['=MINDCASE.ASK_DOC("summarize the document", "test.pdf", 0)'],
  },
  {
    id: "20",
    name: ".ASK_DIR",
    description: "Answers a question from a collection of documents",
    parameters: [
      {
        name: "query",
        description: "Input query in natural language",
        dataType: "string",
        example: ["What is the value of the stock XYZ?"],
        required: true,
      },
      {
        name: "folder_name",
        description: "Name of your folder",
        dataType: "string",
        example: ["New Folder"],
        required: true,
      },
      {
        name: "output_format",
        description: "Output style (0: cell, 1: cols, 2: rows, 3: table)",
        dataType: "number",
        example: [0],
        required: false,
      },
    ],
    examples: ['=MINDCASE.ASK_DIR("summarize all the documents in", "New Folder", 0)'],
  },
  {
    id: "18",
    name: ".ALL_PDF_DATA",
    description: "Extracts all the relevant data from given PDF",
    parameters: [
      {
        name: "file_name",
        description: "Name of your uploaded file",
        dataType: "string",
        example: ["test.pdf"],
        required: true,
      },
    ],
    examples: ['=MINDCASE.ALL_PDF_DATA("test.pdf")'],
  },
];

export const functionTypes = [
  {
    name: "General Functions",
    imgUrl: "../../../../../assets/chat-doc.svg",
    functions: [".ASK"],
  },
  {
    name: "Web Functions",
    imgUrl: "../../../../../assets/Text edit icon.svg",
    functions: [".ASK_WEB", ".EXTRACT_FROM_WEBPAGE", ".EXTRACT_WITH_PAGINATION"],
  },
  {
    name: "Database Functions",
    imgUrl: "../../../../../assets/Text edit icon.svg",
    functions: [".WORLD_BANK", ".YAHOO_FINANCE", ".GET_LINKEDIN_DATA", ".LINKEDIN_URLS", ".GET_EMAIL"],
  },
  {
    name: "Document Chat",
    imgUrl: "../../../../../assets/Text edit icon.svg",
    functions: [".ASK_DOC", ".ASK_DIR", ".ALL_PDF_DATA"],
  },
  {
    name: "Custom Functions",
    imgUrl: "../../../../../assets/text-analysis.svg",
    functions: [".LATEST_STARTUP_FUNDING", ".GET_COMPANY_DATA"],
  },
  {
    name: "Helper Functions",
    imgUrl: "../../../../../assets/text-analysis.svg",
    functions: [".TAG", ".SUMMARIZE", ".TRANSLATE", ".STANDARDIZE_UNITS", ".EXTRACT", ".CLASSIFY"],
  },
];
