export const pricingData = {
  header: "Choose a plan right for you",
  subheader: "Try our basic plan risk free for 30 days",
  annual: {
    plans: [
      {
        id: 1,
        name: "Free",
        plan_id: "plan_PV4oAma7zkfaQQ",
        usdPrice: "$0",
        inrPrice: "₹0",
        description: "For personal use or getting started.",
        features: [
          { name: "1,000 Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Limited Web Access", included: true },
          { name: "No Document Uploads", included: false },
          { name: "User Management", included: false },
          { name: "No Custom Agents", included: false },
          { name: "Email Support", included: false },
        ],
        isPopular: false,
        variant: "light",
      },
      {
        id: 2,
        name: "Starter",
        plan_id: "plan_PXoMGkEvPitOyK",
        usdPrice: "$490",
        inrPrice: "₹39999",
        price: "$490",
        description: "For users looking to experience more features.",
        features: [
          { name: "2,500 Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Unlimited Web Access", included: true },
          { name: "No Document Uploads", included: false },
          { name: "User Management", included: false },
          { name: "No Custom Agents", included: false },
          { name: "Email Support", included: false },
        ],
        isPopular: false,
        variant: "light",
      },
      {
        id: 3,
        name: "Professional",
        plan_id: "plan_PXoLVz1zCSLaSQ",
        usdPrice: "$790",
        inrPrice: "₹59999",
        description: "For professionals looking to unlock full potential.",
        features: [
          { name: "10,000 Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Unlimited Web Access", included: true },
          { name: "Chat with Documents", included: true },
          { name: "User Management", included: false },
          { name: "No Custom Agents", included: false },
          { name: "Email Support", included: false },
        ],
        isPopular: true,
        variant: "light",
      },
      {
        id: 4,
        name: "Teams",
        usdPrice: "Custom",
        inrPrice: "Custom",
        plan_id: "plan_PUaY9wSrMs2NUK",
        description: "For enterprises and startups with large teams.",
        features: [
          { name: "Unlimited Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Unlimited Web Access", included: true },
          { name: "Chat with Documents", included: true },
          { name: "User Management", included: true },
          { name: "Custom Agents", included: true },
          { name: "24/7 Priority Support", included: true },
        ],
        isPopular: false,
        variant: "light",
      },
    ],
  },
  monthly: {
    plans: [
      {
        id: 1,
        name: "Free",
        usdPrice: "$0",
        inrPrice: "₹0",
        plan_id: "plan_PUZEmeZQxX1YdR",
        description: "For personal use or getting started.",
        features: [
          { name: "1,000 Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Limited Web Access", included: true },
          { name: "No Document Uploads", included: false },
          { name: "User Management", included: false },
          { name: "No Custom Agents", included: false },
          { name: "Email Support", included: false },
        ],
        isPopular: false,
        variant: "light",
      },
      {
        id: 2,
        name: "Starter",
        plan_id: "plan_PXoLybUTcXgHw6",
        usdPrice: "$49",
        inrPrice: "₹3999",
        description: "For users looking to experience more features.",
        features: [
          { name: "2,500 Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Unlimited Web Access", included: true },
          { name: "No Document Uploads", included: false },
          { name: "User Management", included: false },
          { name: "No Custom Agents", included: false },
          { name: "Email Support", included: false },
        ],
        isPopular: false,
        variant: "light",
      },
      {
        id: 3,
        name: "Professional",
        plan_id: "plan_PV4oAma7zkfaQQ",
        usdPrice: "$79",
        inrPrice: "₹5999",
        description: "For professionals looking to unlock full potential.",
        features: [
          { name: "10,000 Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Unlimited Web Access", included: true },
          { name: "Chat with Documents", included: true },
          { name: "User Management", included: false },
          { name: "No Custom Agents", included: false },
          { name: "Email Support", included: false },
        ],
        isPopular: true,
        variant: "light",
      },
      {
        id: 4,
        name: "Teams",
        usdPrice: "Custom",
        inrPrice: "Custom",
        plan_id: "plan_PUaY9wSrMs2NUK",
        description: "For enterprises and startups with large teams.",
        features: [
          { name: "Unlimited Credits", included: true },
          { name: "Access to Pre-Built Functions", included: true },
          { name: "Unlimited Web Access", included: true },
          { name: "Chat with Documents", included: true },
          { name: "User Management", included: true },
          { name: "Custom Agents", included: true },
          { name: "24/7 Priority Support", included: true },
        ],
        isPopular: false,
        variant: "light",
      },
    ],
  },
};
