import { makeStyles, tokens } from "@fluentui/react-components";
import { Colors, Dimensions } from "../../utils/constants";
const useStyles = makeStyles({
  root: {
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    height: "600px",
  },
  tooltip: {
    position: "absolute",
    left: "6px",
    color: "#ffffff",
    top: "6px",
  },
  drawerTooltip: {
    position: "absolute",
    left: "12px",
    color: "#ffffff",
    top: "16px",
  },
  subheaderTooltip: {
    position: "absolute",
    left: "8px",
    color: "#ffffff",
    top: "8px",
  },
  sectionHeader: {
    marginLeft: "18px",
    marginBottom: "14px",
    color: "#CACACA",
  },
  navBody: {
    background: Colors.primary,
    color: `${Colors.white} !important`,
    padding: "0px",
  },
  navDivider: {
    width: "86%",
    opacity: "0.3",
    margin: "0px auto",
    height: "0.2px",
    marginBottom: "16px",
  },
  navItemsParent: {
    marginInline: "18px",
    backgroundColor: "#1e2a38",
    height: "94.5%",
    paddingTop: "6px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    borderRadius: "12px",
    marginTop: "10px",
  },
  headerContainer: {
    display: "flex",
    backgroundColor: Colors.primary,
    position: "relative",
    height: "32px",
    padding: Dimensions.spacing.extraSmall,
    justifyContent: "center",
  },
  headerText1: {
    fontSize: "16px",
    fontWeight: "700",
    letterSpacing: "1.5px",
    color: "white",
  },
  drawer: {
    border: "none",
    width: "80%",
  },
  navItemContainer: {
    background: "transparent",
    position: "relative",
    fontSize: "13px",
    paddingInline: "18px",
    color: "#CDD1DC",
    paddingBlock: "8px",
    fontWeight: "400",
    ":hover": {
      backgroundColor: "#1e2a38",
    },
    ":after": {
      display: "none",
    },
  },
  linkExt: {
    width: "16px",
    height: "16px",
    position: "absolute",
    right: "6px",
  },
  headerPathName: {
    fontSize: "16px",
    fontWeight: "500",
    color: "white",
    textTransform: "capitalize",
  },
  subHeaderContainer: {
    display: "flex",
    backgroundColor: Colors.primary,
    position: "relative",
    color: "#ffffff",
    height: "32px",
    padding: Dimensions.spacing.extraSmall,
    justifyContent: "center",
  },
  logoContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#ffffff",
    gap: Dimensions.spacing.extraSmall,
  },
  logoText: {
    fontSize: Dimensions.fonts.large,
    letterSpacing: "0.6px",
    fontWeight: "900",
  },
  content: {
    flex: "1",
    padding: "16px",
    display: "grid",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  field: {
    display: "flex",
    marginTop: "4px",
    marginLeft: "8px",
    flexDirection: "column",
    gridRowGap: tokens.spacingVerticalS,
  },
  appItem: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    borderRadius: Dimensions.spacing.extraSmall,
    marginBottom: "10px",
    paddingBlock: Dimensions.spacing.extraSmall,
    gap: Dimensions.spacing.medium,
    alignItems: "center",
  },
  disabled: {
    cursor: "not-allowed",
    color: "gray!important",
  },
  planPill: {
    color: "white",
    background: Colors.accent,
    width: "30px",
    height: "15px",
    display: "flex",
    fontSize: "10px",
    lineHeight: "10px",
    fontWeight: "700",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "12px",
    position: "absolute",
    top: "30%",
    right: "6px",
  },
  currentPath: {
    color: Colors.accent,
  },
  loginAppItem: {
    marginBottom: Dimensions.spacing.large,
    display: "flex",
    cursor: "pointer",
    fontSize: "13px",
    color: "#CDD1DC",
    gap: Dimensions.spacing.small,
    marginLeft: "18px",
    alignItems: "center",
  },
});

export const useHeaderstyles = () => {
  return useStyles();
};
